services:
  hamming-discovery-agent-backend:
    image: hamming-discovery-agent:latest
    container_name: hamming-discovery-agent-backend
    build: .
    ports:
      - "8000:8000"
    env_file:
      - local-config.env